# Generated by Django 2.0.1 on 2018-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
