# Generated by Django 2.0.1 on 2018-01-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_user',
            new_name='user',
        ),
    ]
