# Generated by Django 2.0.1 on 2018-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180103_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
