# Generated by Django 2.0.1 on 2018-01-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180103_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='user',
        ),
    ]
